export const lunexEndpoints = [
  "GET /wp-json/lunex/v1/home",
  "GET /wp-json/lunex/v1/settings",
  "GET /wp-json/lunex/v1/menus",
  "GET /wp-json/lunex/v1/cart",
  "POST /wp-json/lunex/v1/cart/items",
  "PUT /wp-json/lunex/v1/cart/items/{key}",
  "DELETE /wp-json/lunex/v1/cart/items/{key}",
  "POST /wp-json/lunex/v1/coupon",
  "DELETE /wp-json/lunex/v1/coupon/{code}",
  "GET /wp-json/lunex/v1/checkout/options",
  "POST /wp-json/lunex/v1/checkout",
  "POST /wp-json/lunex/v1/auth/login",
  "POST /wp-json/lunex/v1/auth/register",
  "POST /wp-json/lunex/v1/auth/logout",
  "GET /wp-json/lunex/v1/me",
  "PUT /wp-json/lunex/v1/me",
  "GET /wp-json/lunex/v1/orders",
  "GET /wp-json/lunex/v1/orders/{id}",
  "GET /wp-json/lunex/v1/order-tracking",
  "GET /wp-json/lunex/v1/wishlist",
  "POST /wp-json/lunex/v1/wishlist",
  "DELETE /wp-json/lunex/v1/wishlist/{productId}",
  "POST /wp-json/lunex/v1/contact",
];
